import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import PhotoGallery from '../src/components/PhotoGallery/PhotoGallery'
import Settings from '../src/components/Settings/Settings'

import style from '../styles/Home.module.sass'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Photo Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.homeContainer}>
          <Settings/>
          <PhotoGallery/>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
